/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class Category {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Category(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Category obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_Category(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    GumtreeNetJNI.Category_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return GumtreeNetJNI.Category_id_get(swigCPtr, this);
  }

  public void setName(String value) {
    GumtreeNetJNI.Category_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return GumtreeNetJNI.Category_name_get(swigCPtr, this);
  }

}
