/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class GTAdList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GTAdList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTAdList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_GTAdList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GTAdList() {
    this(GumtreeNetJNI.new_GTAdList__SWIG_0(), true);
  }

  public GTAdList(long n) {
    this(GumtreeNetJNI.new_GTAdList__SWIG_1(n), true);
  }

  public long size() {
    return GumtreeNetJNI.GTAdList_size(swigCPtr, this);
  }

  public long capacity() {
    return GumtreeNetJNI.GTAdList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    GumtreeNetJNI.GTAdList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return GumtreeNetJNI.GTAdList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    GumtreeNetJNI.GTAdList_clear(swigCPtr, this);
  }

  public void add(GTAd x) {
    GumtreeNetJNI.GTAdList_add(swigCPtr, this, GTAd.getCPtr(x), x);
  }

  public GTAd get(int i) {
    long cPtr = GumtreeNetJNI.GTAdList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new GTAd(cPtr, true);
  }

  public void set(int i, GTAd val) {
    GumtreeNetJNI.GTAdList_set(swigCPtr, this, i, GTAd.getCPtr(val), val);
  }

}
