/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class GTAdPage {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected GTAdPage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTAdPage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_GTAdPage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GTAdPage() {
    this(GumtreeNetJNI.new_GTAdPage(), true);
  }

  public void setNumFound(int value) {
    GumtreeNetJNI.GTAdPage_numFound_set(swigCPtr, this, value);
  }

  public int getNumFound() {
    return GumtreeNetJNI.GTAdPage_numFound_get(swigCPtr, this);
  }

  public void setNextLink(String value) {
    GumtreeNetJNI.GTAdPage_nextLink_set(swigCPtr, this, value);
  }

  public String getNextLink() {
    return GumtreeNetJNI.GTAdPage_nextLink_get(swigCPtr, this);
  }

  public void setPrevLink(String value) {
    GumtreeNetJNI.GTAdPage_prevLink_set(swigCPtr, this, value);
  }

  public String getPrevLink() {
    return GumtreeNetJNI.GTAdPage_prevLink_get(swigCPtr, this);
  }

  public void setSelfLink(String value) {
    GumtreeNetJNI.GTAdPage_selfLink_set(swigCPtr, this, value);
  }

  public String getSelfLink() {
    return GumtreeNetJNI.GTAdPage_selfLink_get(swigCPtr, this);
  }

  public void setSelfPublicLink(String value) {
    GumtreeNetJNI.GTAdPage_selfPublicLink_set(swigCPtr, this, value);
  }

  public String getSelfPublicLink() {
    return GumtreeNetJNI.GTAdPage_selfPublicLink_get(swigCPtr, this);
  }

}
