/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class GTAd {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected GTAd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTAd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_GTAd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GTAd() {
    this(GumtreeNetJNI.new_GTAd(), true);
  }

  public void setPrice(Price value) {
    GumtreeNetJNI.GTAd_price_set(swigCPtr, this, Price.getCPtr(value), value);
  }

  public Price getPrice() {
    long cPtr = GumtreeNetJNI.GTAd_price_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Price(cPtr, false);
  }

  public void setCategory(Category value) {
    GumtreeNetJNI.GTAd_category_set(swigCPtr, this, Category.getCPtr(value), value);
  }

  public Category getCategory() {
    long cPtr = GumtreeNetJNI.GTAd_category_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Category(cPtr, false);
  }

  public void setId(String value) {
    GumtreeNetJNI.GTAd_id_set(swigCPtr, this, value);
  }

  public String getId() {
    return GumtreeNetJNI.GTAd_id_get(swigCPtr, this);
  }

  public void setTitle(String value) {
    GumtreeNetJNI.GTAd_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return GumtreeNetJNI.GTAd_title_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    GumtreeNetJNI.GTAd_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return GumtreeNetJNI.GTAd_description_get(swigCPtr, this);
  }

  public void setFull_address(String value) {
    GumtreeNetJNI.GTAd_full_address_set(swigCPtr, this, value);
  }

  public String getFull_address() {
    return GumtreeNetJNI.GTAd_full_address_get(swigCPtr, this);
  }

  public void setLongitude(double value) {
    GumtreeNetJNI.GTAd_longitude_set(swigCPtr, this, value);
  }

  public double getLongitude() {
    return GumtreeNetJNI.GTAd_longitude_get(swigCPtr, this);
  }

  public void setLatitude(double value) {
    GumtreeNetJNI.GTAd_latitude_set(swigCPtr, this, value);
  }

  public double getLatitude() {
    return GumtreeNetJNI.GTAd_latitude_get(swigCPtr, this);
  }

  public void setNeighborhood(String value) {
    GumtreeNetJNI.GTAd_neighborhood_set(swigCPtr, this, value);
  }

  public String getNeighborhood() {
    return GumtreeNetJNI.GTAd_neighborhood_get(swigCPtr, this);
  }

  public void setEmail(String value) {
    GumtreeNetJNI.GTAd_email_set(swigCPtr, this, value);
  }

  public String getEmail() {
    return GumtreeNetJNI.GTAd_email_get(swigCPtr, this);
  }

  public void setPhone(String value) {
    GumtreeNetJNI.GTAd_phone_set(swigCPtr, this, value);
  }

  public String getPhone() {
    return GumtreeNetJNI.GTAd_phone_get(swigCPtr, this);
  }

  public void setRank(int value) {
    GumtreeNetJNI.GTAd_rank_set(swigCPtr, this, value);
  }

  public int getRank() {
    return GumtreeNetJNI.GTAd_rank_get(swigCPtr, this);
  }

  public void setAd_status(String value) {
    GumtreeNetJNI.GTAd_ad_status_set(swigCPtr, this, value);
  }

  public String getAd_status() {
    return GumtreeNetJNI.GTAd_ad_status_get(swigCPtr, this);
  }

  public void setSelf_public_website(String value) {
    GumtreeNetJNI.GTAd_self_public_website_set(swigCPtr, this, value);
  }

  public String getSelf_public_website() {
    return GumtreeNetJNI.GTAd_self_public_website_get(swigCPtr, this);
  }

  public void setNormalPicuteLinks(StringList value) {
    GumtreeNetJNI.GTAd_normalPicuteLinks_set(swigCPtr, this, StringList.getCPtr(value), value);
  }

  public StringList getNormalPicuteLinks() {
    long cPtr = GumtreeNetJNI.GTAd_normalPicuteLinks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

}
