/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class GumtreeClient {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected GumtreeClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GumtreeClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_GumtreeClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GumtreeClient() {
    this(GumtreeNetJNI.new_GumtreeClient(), true);
  }

}
