/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class Price {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Price(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Price obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_Price(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurrency(String value) {
    GumtreeNetJNI.Price_currency_set(swigCPtr, this, value);
  }

  public String getCurrency() {
    return GumtreeNetJNI.Price_currency_get(swigCPtr, this);
  }

  public void setAmount(double value) {
    GumtreeNetJNI.Price_amount_set(swigCPtr, this, value);
  }

  public double getAmount() {
    return GumtreeNetJNI.Price_amount_get(swigCPtr, this);
  }

  public void setType(String value) {
    GumtreeNetJNI.Price_type_set(swigCPtr, this, value);
  }

  public String getType() {
    return GumtreeNetJNI.Price_type_get(swigCPtr, this);
  }

}
