/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class StringList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StringList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_StringList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringList() {
    this(GumtreeNetJNI.new_StringList__SWIG_0(), true);
  }

  public StringList(long n) {
    this(GumtreeNetJNI.new_StringList__SWIG_1(n), true);
  }

  public long size() {
    return GumtreeNetJNI.StringList_size(swigCPtr, this);
  }

  public long capacity() {
    return GumtreeNetJNI.StringList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    GumtreeNetJNI.StringList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return GumtreeNetJNI.StringList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    GumtreeNetJNI.StringList_clear(swigCPtr, this);
  }

  public void add(String x) {
    GumtreeNetJNI.StringList_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return GumtreeNetJNI.StringList_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    GumtreeNetJNI.StringList_set(swigCPtr, this, i, val);
  }

}
