/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class GTAdQueryRequest {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected GTAdQueryRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTAdQueryRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_GTAdQueryRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GTAdQueryRequest() {
    this(GumtreeNetJNI.new_GTAdQueryRequest__SWIG_0(), true);
  }

  public GTAdQueryRequest(String baseUrl) {
    this(GumtreeNetJNI.new_GTAdQueryRequest__SWIG_1(baseUrl), true);
  }

  public static void setKeyQ(String value) {
    GumtreeNetJNI.GTAdQueryRequest_KeyQ_set(value);
  }

  public static String getKeyQ() {
    return GumtreeNetJNI.GTAdQueryRequest_KeyQ_get();
  }

  public static void setKeySize(String value) {
    GumtreeNetJNI.GTAdQueryRequest_KeySize_set(value);
  }

  public static String getKeySize() {
    return GumtreeNetJNI.GTAdQueryRequest_KeySize_get();
  }

  public static void setKeyPage(String value) {
    GumtreeNetJNI.GTAdQueryRequest_KeyPage_set(value);
  }

  public static String getKeyPage() {
    return GumtreeNetJNI.GTAdQueryRequest_KeyPage_get();
  }

  public static void setKeyPriceCurrency(String value) {
    GumtreeNetJNI.GTAdQueryRequest_KeyPriceCurrency_set(value);
  }

  public static String getKeyPriceCurrency() {
    return GumtreeNetJNI.GTAdQueryRequest_KeyPriceCurrency_get();
  }

  public static void setKeyMinPrice(String value) {
    GumtreeNetJNI.GTAdQueryRequest_KeyMinPrice_set(value);
  }

  public static String getKeyMinPrice() {
    return GumtreeNetJNI.GTAdQueryRequest_KeyMinPrice_get();
  }

  public static void setKeyMaxPrice(String value) {
    GumtreeNetJNI.GTAdQueryRequest_KeyMaxPrice_set(value);
  }

  public static String getKeyMaxPrice() {
    return GumtreeNetJNI.GTAdQueryRequest_KeyMaxPrice_get();
  }

  public static void setKeySortType(String value) {
    GumtreeNetJNI.GTAdQueryRequest_KeySortType_set(value);
  }

  public static String getKeySortType() {
    return GumtreeNetJNI.GTAdQueryRequest_KeySortType_get();
  }

  public static void setKeyPictureRequired(String value) {
    GumtreeNetJNI.GTAdQueryRequest_KeyPictureRequired_set(value);
  }

  public static String getKeyPictureRequired() {
    return GumtreeNetJNI.GTAdQueryRequest_KeyPictureRequired_get();
  }

  public static void setKeyIncludeTopAds(String value) {
    GumtreeNetJNI.GTAdQueryRequest_KeyIncludeTopAds_set(value);
  }

  public static String getKeyIncludeTopAds() {
    return GumtreeNetJNI.GTAdQueryRequest_KeyIncludeTopAds_get();
  }

  public void setBaseUrl(String url) {
    GumtreeNetJNI.GTAdQueryRequest_setBaseUrl(swigCPtr, this, url);
  }

  public String baseUrl() {
    return GumtreeNetJNI.GTAdQueryRequest_baseUrl(swigCPtr, this);
  }

  public void setQ(String keyword) {
    GumtreeNetJNI.GTAdQueryRequest_setQ(swigCPtr, this, keyword);
  }

  public String q() {
    return GumtreeNetJNI.GTAdQueryRequest_q(swigCPtr, this);
  }

  public void setSize(int size) {
    GumtreeNetJNI.GTAdQueryRequest_setSize(swigCPtr, this, size);
  }

  public int size() {
    return GumtreeNetJNI.GTAdQueryRequest_size(swigCPtr, this);
  }

  public void setPage(int page) {
    GumtreeNetJNI.GTAdQueryRequest_setPage(swigCPtr, this, page);
  }

  public int page() {
    return GumtreeNetJNI.GTAdQueryRequest_page(swigCPtr, this);
  }

  public void setPriceCurrency(String currency) {
    GumtreeNetJNI.GTAdQueryRequest_setPriceCurrency(swigCPtr, this, currency);
  }

  public String priceCurrency() {
    return GumtreeNetJNI.GTAdQueryRequest_priceCurrency(swigCPtr, this);
  }

  public void setMinPrice(int price) {
    GumtreeNetJNI.GTAdQueryRequest_setMinPrice(swigCPtr, this, price);
  }

  public int minPrice() {
    return GumtreeNetJNI.GTAdQueryRequest_minPrice(swigCPtr, this);
  }

  public void setMaxPrice(int price) {
    GumtreeNetJNI.GTAdQueryRequest_setMaxPrice(swigCPtr, this, price);
  }

  public int maxPrice() {
    return GumtreeNetJNI.GTAdQueryRequest_maxPrice(swigCPtr, this);
  }

  public void setSortType(String type) {
    GumtreeNetJNI.GTAdQueryRequest_setSortType(swigCPtr, this, type);
  }

  public String sortType() {
    return GumtreeNetJNI.GTAdQueryRequest_sortType(swigCPtr, this);
  }

  public void setPictureRequired(boolean required) {
    GumtreeNetJNI.GTAdQueryRequest_setPictureRequired(swigCPtr, this, required);
  }

  public boolean pictureRequired() {
    return GumtreeNetJNI.GTAdQueryRequest_pictureRequired(swigCPtr, this);
  }

  public void setIncludeTopAds(boolean included) {
    GumtreeNetJNI.GTAdQueryRequest_setIncludeTopAds(swigCPtr, this, included);
  }

  public boolean includeTopAds() {
    return GumtreeNetJNI.GTAdQueryRequest_includeTopAds(swigCPtr, this);
  }

  public GTAdQueryRequest requestForNextPage() {
    long cPtr = GumtreeNetJNI.GTAdQueryRequest_requestForNextPage(swigCPtr, this);
    return (cPtr == 0) ? null : new GTAdQueryRequest(cPtr, true);
  }

  public GTAdQueryRequest requestForPrevPage() {
    long cPtr = GumtreeNetJNI.GTAdQueryRequest_requestForPrevPage(swigCPtr, this);
    return (cPtr == 0) ? null : new GTAdQueryRequest(cPtr, true);
  }

  public String toUrl() {
    return GumtreeNetJNI.GTAdQueryRequest_toUrl(swigCPtr, this);
  }

  public void set_baseUrl(String value) {
    GumtreeNetJNI.GTAdQueryRequest__baseUrl_set(swigCPtr, this, value);
  }

  public String get_baseUrl() {
    return GumtreeNetJNI.GTAdQueryRequest__baseUrl_get(swigCPtr, this);
  }

  public void set_params(StringMap value) {
    GumtreeNetJNI.GTAdQueryRequest__params_set(swigCPtr, this, StringMap.getCPtr(value), value);
  }

  public StringMap get_params() {
    long cPtr = GumtreeNetJNI.GTAdQueryRequest__params_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringMap(cPtr, false);
  }

}
