/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class GTAdQueryResponse {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected GTAdQueryResponse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTAdQueryResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_GTAdQueryResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GTAdQueryResponse() {
    this(GumtreeNetJNI.new_GTAdQueryResponse(), true);
  }

  public void setAds(GTAdList value) {
    GumtreeNetJNI.GTAdQueryResponse_ads_set(swigCPtr, this, GTAdList.getCPtr(value), value);
  }

  public GTAdList getAds() {
    long cPtr = GumtreeNetJNI.GTAdQueryResponse_ads_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GTAdList(cPtr, false);
  }

  public void setPaging(GTAdPage value) {
    GumtreeNetJNI.GTAdQueryResponse_paging_set(swigCPtr, this, GTAdPage.getCPtr(value), value);
  }

  public GTAdPage getPaging() {
    long cPtr = GumtreeNetJNI.GTAdQueryResponse_paging_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GTAdPage(cPtr, true);
  }

  public void setJsonPayload(String value) {
    GumtreeNetJNI.GTAdQueryResponse_jsonPayload_set(swigCPtr, this, value);
  }

  public String getJsonPayload() {
    return GumtreeNetJNI.GTAdQueryResponse_jsonPayload_get(swigCPtr, this);
  }

}
