/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gumtree.jni;

public class GTAdQuery {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected GTAdQuery(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTAdQuery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GumtreeNetJNI.delete_GTAdQuery(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GTAdQuery() {
    this(GumtreeNetJNI.new_GTAdQuery(), true);
  }

  public int query(GTAdQueryRequest request, GTAdQueryResponse response) {
    return GumtreeNetJNI.GTAdQuery_query(swigCPtr, this, GTAdQueryRequest.getCPtr(request), request, GTAdQueryResponse.getCPtr(response), response);
  }

}
